### ISSUE TITLE
concatenate_tracks not working for temporal_coherence?

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/mimtpy#13]
Hi @ranneylxr 
For the example below the concatenation is working well for datatype `velocity` and `timeseries`, but  not for `temporalCoherence` and `avgSpatialCoherence`.  The S1* files looks good. Are those options not fully supported yet or is that a bug? 
Thank you
Falk

```
concatenate_chunks.py --chunks ChamanChunk{32,33}SenDT78 --project ChamanBigSenDT78 --datatype temporalCoherence  --outdir mimtpy
```
```
/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy

Go to project dir: /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy

the output dir for temporalCoherence is /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy/temporalCoherence.


The HDFEOS file is S1_IW123_078_0483_0489_20141023_XXXXXXXX.he5

Go to project dir: /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy

the output dir for temporalCoherence is /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy/temporalCoherence.


The HDFEOS file is S1_IW123_078_0480_0485_20141023_XXXXXXXX.he5

the output dir for concatenation is /scratch1/05861/tg851601/ChamanBigSenDT78/mimtpy/temporalCoherence.

track_offset.py /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy/temporalCoherence/temporalCoherence.h5 /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy/temporalCoherence/temporalCoherence.h5 --output temporalCoherence_track --outdir /scratch1/05861/tg851601/ChamanBigSenDT78/mimtpy/temporalCoherence/
Traceback (most recent call last):
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 264, in <module>
    main()
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 260, in main
    concatenation_chunks(chunks, project, datatype, outdir)
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 201, in concatenation_chunks
    mimtpy.track_offset.main(scp_args.split())   
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/track_offset.py", line 496, in main
    m_atr = readfile.read_attribute("".join(inps.master))
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MintPy/mintpy/utils/readfile.py", line 739, in read_attribute
    raise Exception(msg)
Exception: input file not existed: /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy/temporalCoherence/temporalCoherence.h5
current directory: /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy
```

```
concatenate_chunks.py --chunks ChamanChunk{32,33}SenDT78 --project ChamanBigSenDT78 --datatype avgSpatialCoherence  --outdir mimtpy
/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy

Go to project dir: /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy

the output dir for avgSpatialCoherence is /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy/avgSpatialCoherence.


The HDFEOS file is S1_IW123_078_0483_0489_20141023_XXXXXXXX.he5

Go to project dir: /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy

the output dir for avgSpatialCoherence is /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy/avgSpatialCoherence.


The HDFEOS file is S1_IW123_078_0480_0485_20141023_XXXXXXXX.he5

the output dir for concatenation is /scratch1/05861/tg851601/ChamanBigSenDT78/mimtpy/avgSpatialCoherence.

track_offset.py /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy/avgSpatialCoherence/avgSpatialCoherence.h5 /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy/avgSpatialCoherence/avgSpatialCoherence.h5 --output avgSpatialCoherence_track --outdir /scratch1/05861/tg851601/ChamanBigSenDT78/mimtpy/avgSpatialCoherence/
Traceback (most recent call last):
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 264, in <module>
    main()
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 260, in main
    concatenation_chunks(chunks, project, datatype, outdir)
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/concatenate_chunks.py", line 201, in concatenation_chunks
    mimtpy.track_offset.main(scp_args.split())   
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MimtPy/mimtpy/track_offset.py", line 496, in main
    m_atr = readfile.read_attribute("".join(inps.master))
  File "/work2/05861/tg851601/stampede2/codet/rsmas_insar/sources/MintPy/mintpy/utils/readfile.py", line 739, in read_attribute
    raise Exception(msg)
Exception: input file not existed: /scratch1/05861/tg851601/ChamanChunk32SenDT78/mintpy/avgSpatialCoherence/avgSpatialCoherence.h5
current directory: /scratch1/05861/tg851601/ChamanChunk33SenDT78/mintpy
```
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11162588/155851969-89a2d4d9-5f6d-48d8-b931-d4717e1cb1c6.png">

**Comment by ranneylxr** [comment]
Hi @falkamelung 
This error occured becaue I didn't update the modified version in time...
I have uploaded the modified version now. 
In the modified version, it can produce the concatenated S1 data and automatically plot the conatenated data at last.

**Comment by falkamelung** [comment]
Closing because it is working
